### PR TITLE
push short Docker tag to repo instead of long tag

### PR DESCRIPTION
**Pull request by wshands**
push short Docker tag to repo instead of long tag

### CODE REVIEW

**Comment by wshands** [comment]
John, Jenkins reports The Jenkins build failed with Build timed out (after 30 minutes). Marking the build as failed. How do I increase the timeout?

**Comment by jvivian** [comment]
jenkins, test this please.

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by wshands** [comment]
Jenkins, test this please.

**Comment by jvivian** [comment]
@wshands — Hey, that did it! I'll take a quick look then merge.

**Pull request merged**
