### PR TITLE
Enable Kallisto only processing; addresses #116

### LINKED ISSUE #116: Support for Kallisto only determining expression counts
Provide support for using only Kallisto to determine expression counts. This can be done by allowing empty strings for the Star and RSEM paths

### PR DESCRIPTION
**Pull request by wshands**
Enable Kallisto only processing by accepting empty strings for
Star and RSEM paths
Fixes #116

### CODE REVIEW

**Comment by wshands** [comment]
This will help FLXBIO run your pipeline on their data. I thought this was needed in the next week or so but found out we may not be able to process their data for them due to University restrictions, but this is all being sorted out so a new release is needed soon in case we can go forward. Next week?

**Comment by jvivian** [comment]
@wshands — sounds good, I've forgotten exactly how the release process works for the docker containers. Did we ever fix it so the versions are updated automatically?

**Comment by wshands** [comment]
Yes versions are updated automatically, we just have to make sure the line in rnaseq-cgl-pipeline.cwl:
dockerPull: "quay.io/ucsc_cgl/rnaseq-cgl-pipeline:3.3.5-1.12.3"
has the new version string; in this case I changed it assuming the new release would be 3.3.5; let me know if that is not correct.

**Comment by jvivian** [comment]
Will merge, then cherry pick over to the release branch in preparation for releasing 3.3.5

**Pull request merged**
